#!/bin/sh

# GPL v3 license

VERSION="0.1"

usage () {
    cat << EOF >&2
    
Usage: $0 [--version] [-h | --help] [-c | --candle CANDLE_NUM]
Print a festive Adventskranz on the CLI.
  --version   Show version
  -h | --help Show help
  -c | --candle CANDLE_NUM Give the number of burning candles
    
EOF
}

CANDLE_NUM=0

while [ -n "$1" ]; do
    # Stop reading when we've run out of options.
    [ "$(printf "%s" "$1" | cut -c 1)" != "-" ] && break

    if [ "$1" = "--version" ]; then
        echo "v$VERSION"
        exit 0
    fi
    if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
        usage
        exit 0
    fi
    if [ "$1" = "-c" ] || [ "$1" = "--candle" ]; then
        shift
        CANDLE_NUM=$1
        if [[ $CANDLE_NUM = -* ]]; then
            echo "no time travelling, honey ;)"
            exit 1
        fi
    fi
done

if [ -z $CANDLE_NUM ]; then
     echo please specify how many candles you want to see burn
     exit 1
elif [ $CANDLE_NUM -gt 4 ]; then
     echo ... then you have sleeped through Christmas! / dann hast du Weihnachten verpennt!
     exit 1
else
     full_path=$(realpath $0)
     dir_path=$(dirname $full_path)

     cat $dir_path/candles/ad$CANDLE_NUM.txt
     exit 0
fi
